on:
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: actions/checkout@v2
      - run: npm ci
      - run: node .github/actions/update-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FEED_URL: http://simplecast.fm/podcasts/1034/rss

